StashBuildTrigger: Use isBuildable() instead of isDisabled()
jenkinsci/stash-pullrequest-builder-plugin pull request #80
Opened 2019-04-13 19:45 UTC by proski

```
*  StashBuildTrigger: Use isBuildable() instead of isDisabled()
   
   There are reasons for a job to be non-buildable other than the project
   being disabled. The Jenkins core uses isBuildable(), not isDisabled()
   when deciding whether to run a job.
   
   Don't call stashPullRequestsBuilder.getProject(), use this.job directly.
   Make sure it's not null.
```

This little piece of the pipeline PR would be useful whether we support pipelines or not. It reduces interdependence between classes and matches closer to what Jenkins does internally when deciding whether to run a job.

2019-04-15 09:38 UTC, jakub-bochenski commented
>   Don't call stashPullRequestsBuilder.getProject(), use this.job directly.
   Make sure it's not null.

Can you add to the commit message, that  `this.job` is most likely the same as `stashPullRequestsBuilder.getProject()` (both come from `start()` method)?

2019-04-15 09:39 UTC, jakub-bochenski requested changes
see above

2019-04-16 06:53 UTC, proski commented
Improved the commit comment. Also removed the check for `stashPullRequestsBuilder` being non-null, it's equivalent to `this.job` being non-null.

2019-04-16 16:43 UTC, jakub-bochenski approved these changes

2019-04-24 15:52 UTC, merged